services:
  mysql:
    image: mysql:latest
    container_name: encurtador-url
    environment:
      MYSQL_DATABASE: EncurtadorUrl
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - "mysql-data:/var/lib/mysql"
    ports:
      - "3307:3306"
    restart: always
volumes:
  mysql-data: