spring:
  application:
    name: encurtador

  datasource:
    url: jdbc:mysql://localhost:3307/EncurtadorUrl?useTimezone=true@serverTimeZone=UTC
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
